### ISSUE TITLE
uploader.post function really slow to proceed, fs warning also

### ISSUE THREAD

**Issue by kopax** [arvindr21/blueimp-file-upload-expressjs#32]
Hi,

I am using :
 - nodejs 0.10.35
 - blueimp-file-upload-expressjs 0.3.2
 - blueimp-file-upload (jQuery File Upload) 9.9.1
 - express 4.9.5
 - a 243KB jpeg file

When I upload a file, the post duration takes at least a minutes for a small file.

    2015-01-12T23:15:17+01:00 starting upload with fn uploader.post
    2015-01-12T23:16:19+01:00 end upload with fn uploader.post
    Total upload duration 62835 ms

It can goes up to 200842 ms
I also often have this errors :

    fs: missing callback Error: ENOENT, unlink 'E:\tmp\upload_e39027d4f0f91dd03c4a58da3711e3bf'

My configuration file looks like this

    imageVersions: {
        maxWidth: 1800,
        maxHeight: 'auto',
        xxxlarge: {
            width: 1300,
            height: 'auto'
        },
        xxlarge: {
            width: 9999,
            height: 'auto'
        },
        xlarge: {
            width : 700,
            height: 'auto'
        },
        large: {
            width : 300,
            height: 'auto'
        },
        medium: {
            width : 140,
            height: 'auto'
        },
        xsmall: {
            width: 100,
            height: 'auto'
        }
    }

By the way, considering the `fileInfo.initUrls` function 

    // L170
    Object.keys(options.imageVersions).forEach(function(version) {
          if (_existsSync(
              options.uploadDir + '/' + version + '/' + that.name
            )) {
            that[version + 'Url'] = baseUrl + version + '/' +
              encodeURIComponent(that.name);
          }
        });

My model returned in obj.files should have these URI set  as attributes with proper keys, but instead I have largeUrl and mediumUrl

    "_id" : ObjectId("54b442e2e94c0bc00b6ec4ce"),
    "creationDate" : ISODate("2015-01-12T21:55:46.481Z"),
    "name" : "charlie2.jpg",
    "size" : 908057,
    "type" : "image/jpeg",
    "deleteType" : "DELETE",
    "url" : "http://localhost:8000/upload/charlie2.jpg",
    "deleteUrl" : "http://localhost:8000/upload/charlie2.jpg",
    "largeUrl" : "http://localhost:8000/upload/large/charlie2.jpg",
    "mediumUrl" : "http://localhost:8000/upload/medium/charlie2.jpg",

large and medium folder are automatically created and used, same for xxlarge,xlarge... but URI is not in the model.

I have tried on different computers, all have the lag problem, this must be a problem with the library, I have looked inside the code, can't figure out where it got stuck of so long.

Any ideas ?

**Comment by mycaule** [comment]
Have you tried uploading with another filename like `charlie10.jpg`? Maybe your upload folder isn't so clean.
What model are you talking about by the way?

**Comment by mycaule** [comment]
The `unlink` error is a known issue. With node.js updates, they changed the `fs` library and added callbacks to `unlink`. It still works without callbacks but it has to be fixed in the blueimp-file-upload-expressjs package. 

What you can do on your side is adding a callback to each unlink occurrence and deal with the error properly.

Please try also to disable all the thumbnails, as they are quite big, the problem could come from the `lwip` dependency.

**Comment by kopax** [comment]
I clean my database and upload folder all the time until I understand how to fix this, it can't be this.
I will try to edit blueimp-file-upload-expressjs package and remove all the thumbnails tomorrow after work, I let you know if I get better result

**Comment by mycaule** [comment]
Have you solved the problem?

**Comment by mycaule** [comment]
@kopax As-tu résolu le problème ?

**Comment by mycaule** [comment]
Closed as not reproductible.
